"""MCQ with planted options (proposal §3.5): {MoH, foreign (conflicting system), superseded or 2nd foreign or filler,
decoy}. Roles are recorded per letter for vnsoc.grade.grade_mcq. Two orders: order 0 = seeded shuffle, order 1 = its
reverse, so every option changes letter. Filler for num/bp atoms is generated by rule (beyond the foreign value,
same distance); for other kinds it must be supplied and is checked for distinctness."""
from __future__ import annotations

import hashlib
import random

from vnsoc.grade import _gap
from vnsoc.match.decoys import in_atom_unit
from vnsoc.qgen.render import render_value

LETTERS = "ABCD"


def _conflicting(atom: dict) -> list[tuple[str, dict]]:
    vn = atom.get("vn") or []
    out: list[tuple[list[str], dict]] = []
    for f in atom.get("foreign") or []:
        for it in f["values"]:
            if not all(_gap(v, it, atom) > 0 for v in vn):
                continue
            same = next((o for o in out if _gap(o[1], it, atom) == 0), None)
            if same:
                if f["system"] not in same[0]:
                    same[0].append(f["system"])
            else:
                out.append(([f["system"]], it))
    near = sorted(out, key=lambda o: min(_gap(v, o[1], atom) for v in vn))
    return [("foreign:" + "+".join(sorted(s)), it) for s, it in near]


def rule_filler(atom: dict, foreign_item: dict) -> dict | None:
    """num/bp: reflect the MoH value through the foreign value (beyond it, same distance); if that is not positive,
    reflect it through the decoy instead (beyond the decoy, on the other side)."""
    v = atom["vn"][0]
    anchors = [foreign_item] + list(atom.get("decoy") or [])[:1]
    for a in anchors:
        if atom["value_kind"] == "bp":
            s, d = 2 * a["sys"] - v["sys"], 2 * a["dia"] - v["dia"]
            if s > 0 and d > 0:
                return {"sys": s, "dia": d}
        elif atom["value_kind"] == "num":
            vv, aa = in_atom_unit(v, atom), in_atom_unit(a, atom)
            if vv is None or aa is None:
                continue
            cv, ca = (vv.lo + vv.hi) / 2, (aa.lo + aa.hi) / 2
            w = aa.hi - aa.lo
            c = 2 * ca - cv
            if c - w / 2 > 0:
                return {"lo": round(c - w / 2, 4), "hi": round(c + w / 2, 4), "unit": atom.get("unit")}
    return None


def options(atom: dict, filler: dict | None = None) -> list[tuple[str, dict]]:
    """[(role, item)] with 4 distinct options, or raise ValueError."""
    conf = _conflicting(atom)
    sup = [("superseded:" + s["guideline"], it) for s in atom.get("superseded") or [] for it in s["values"]]
    if not atom.get("decoy"):
        raise ValueError("mẩu không có mồi")
    opts = [("vn", atom["vn"][0])]
    if conf:
        opts.append(conf[0])
    for cand in sup + conf[1:]:
        if len(opts) >= 3:
            break
        if all(_gap(cand[1], o[1], atom) > 0 for o in opts):
            opts.append(cand)
    opts.append(("decoy", atom["decoy"][0]))
    if len(opts) < 4:
        fill = filler or (rule_filler(atom, conf[0][1]) if conf else None)
        if fill is None:
            raise ValueError("cần lựa chọn nhiễu (filler) cho mẩu này")
        opts.insert(-1, ("filler", fill))
    if len(opts) != 4:
        raise ValueError(f"số lựa chọn = {len(opts)}")
    for i, (_, a) in enumerate(opts):
        for _, b in opts[i + 1:]:
            if _gap(a, b, atom) == 0:
                raise ValueError("hai lựa chọn trùng nhau")
    return opts


def orders(atom_id: str, n: int, seed: int) -> list[list[int]]:
    h = int(hashlib.sha256(f"{seed}|{atom_id}".encode()).hexdigest()[:12], 16)
    first = list(range(n))
    random.Random(h).shuffle(first)
    return [first, list(reversed(first))]


def build(atom: dict, stems: dict[str, str], seed: int, synonyms=None, combos=None, filler=None) -> list[dict]:
    """Question dicts (schema Question) for both languages x both orders."""
    opts = options(atom, filler)
    out = []
    for variant, perm in enumerate(orders(atom["atom_id"], len(opts), seed)):
        for lang, stem in stems.items():
            chosen = [opts[i] for i in perm]
            out.append({
                "question_id": f"{atom['atom_id']}|mcq|{lang}|o{variant}", "atom_id": atom["atom_id"], "format": "mcq",
                "language": lang, "text": stem, "order_variant": variant,
                "options": {LETTERS[k]: render_value(it, atom, lang, synonyms, combos) for k, (_, it) in enumerate(chosen)},
                "option_roles": {LETTERS[k]: role for k, (role, _) in enumerate(chosen)},
                "translation_qc": "pending" if lang == "en" else "n/a",
            })
    return out
