"""Decoys are generated by a fixed rule (num/bp) and checked (all kinds). Values are TEST FIXTURES, not data."""
import math

import pytest

from vnsoc.match.decoys import check_decoy, finalize, mirror_decoy


def test_mirror_num_dengue():
    a = {"value_kind": "num", "unit": "ml/kg/h", "vn": [{"lo": 15, "hi": 15}],
         "foreign": [{"system": "WHO_global", "values": [{"lo": 5, "hi": 10}]}]}
    d, rule = mirror_decoy(a)
    assert rule == "mirror_arith" and (d["lo"], d["hi"]) == (20, 25)
    a["decoy"] = [d]
    assert check_decoy(a) == [] and finalize(a)["conflict_status"] == "conflict"


def test_mirror_geom_when_arith_nonpositive():
    a = {"value_kind": "num", "unit": "U/L", "vn": [{"lo": 30, "hi": 30}],
         "foreign": [{"system": "US", "values": [{"lo": 70, "hi": 70}]}]}
    from vnsoc.match.decoys import choose_decoy, decoy_candidates

    # 30²/70 = 12.857... at 0 decimals = 13: already on the 2-significant-digit grid, so it is not moved (to 10)
    d, rule = mirror_decoy(a)
    assert rule == "mirror_geom" and d["lo"] == d["hi"] == 13
    assert decoy_candidates(a) == ([(d, "mirror_geom", "none")], "mirror_geom")
    assert choose_decoy(a)[0] is None                              # 13 is < 2·tol0 = 40 from 30: no valid decoy


def test_mirror_bp():
    a = {"value_kind": "bp", "vn": [{"sys": 140, "dia": 90}],
         "foreign": [{"system": "US", "values": [{"sys": 130, "dia": 80}]}, {"system": "EU_UK", "values": [{"sys": 140, "dia": 90}]}]}
    d, _ = mirror_decoy(a)
    assert (d["sys"], d["dia"]) == (150, 100)


def test_check_decoy_rejects_source_values():
    a = {"value_kind": "schedule", "vn": [{"seq": [0, 3, 7, 14, 28]}],
         "foreign": [{"system": "US", "values": [{"seq": [0, 3, 7, 14]}]}], "decoy": [{"seq": [0, 3, 7, 14]}]}
    assert any("nguồn" in p for p in check_decoy(a))
    a["decoy"] = [{"seq": [0, 3, 7, 21]}]
    assert check_decoy(a) == []
    assert mirror_decoy(a)[0] is None


def test_no_conflict_no_decoy():
    a = {"value_kind": "num", "unit": "mg", "vn": [{"lo": 0.5, "hi": 1.0}],
         "foreign": [{"system": "EU_UK", "values": [{"lo": 0.5, "hi": 0.5}]}]}
    assert mirror_decoy(a) == (None, "không có giá trị nước ngoài xung đột")
    assert finalize(a)["conflict_status"] == "concordant"


def test_mirror_converts_units_first():
    # found by the anaphylaxis pilot agent: foreign 0.01 mg/kg vs MoH µg for a 10 kg child
    a = {"value_kind": "num", "unit": "ug", "context": {"weight_kg": 10, "mg_per_ml": 1},
         "vn": [{"lo": 250, "hi": 250}], "foreign": [{"system": "OTHER", "values": [{"lo": 0.01, "hi": 0.01, "unit": "mg/kg"}]}]}
    d, rule = mirror_decoy(a)
    assert rule == "mirror_arith" and (d["lo"], d["hi"]) == (400, 400) and d["unit"] == "ug"   # 250 + (250 - 100)


def test_choose_decoy_skips_values_of_older_foreign_versions():
    from vnsoc.match.decoys import choose_decoy

    # target SBP >= 65 y: MoH 130-139; ACC/AHA < 130 (as 120-129); JNC8 2014 < 150 recorded as an older US version
    a = {"value_kind": "num", "unit": "mmHg", "vn": [{"lo": 130, "hi": 139}],
         "foreign": [{"system": "US", "values": [{"lo": 120, "hi": 129}]},
                     {"system": "US", "values": [{"lo": 140, "hi": 149}]}]}
    d, rule = mirror_decoy(a)
    assert (d["lo"], d["hi"]) == (140, 149) and check_decoy(dict(a, decoy=[d]))      # arith lands on JNC8-like value
    d2, rule2 = choose_decoy(a)
    assert rule2 in ("mirror_geom", "mirror_far") and check_decoy(dict(a, decoy=[d2])) == []


def test_bp_far_rule():
    a = {"value_kind": "bp", "vn": [{"sys": 140, "dia": 90}], "foreign": [{"system": "US", "values": [{"sys": 130, "dia": 80}]}]}
    assert mirror_decoy(a, "mirror_far")[0]["sys"] == 160


def test_check_decoy_blames_decoy_only_when_it_causes_indistinguishable():
    # MoH ULN 30; US 35 equals the superseded MoH value 35 -> indistinguishable before any decoy
    a = {"value_kind": "num", "unit": "U/L", "vn": [{"lo": 30, "hi": 30}],
         "foreign": [{"system": "US", "values": [{"lo": 35, "hi": 35}]}],
         "superseded": [{"guideline": "3310/2019", "values": [{"lo": 35, "hi": 35}]}], "decoy": [{"lo": 25, "hi": 25}]}
    assert finalize(dict(a, decoy=[]))["conflict_status"] == "indistinguishable"
    assert check_decoy(a) == []


def test_decoy_inside_tolerance_of_a_source_is_rejected():
    # malaria OCR audit: decoy 0.2 sits 0.05 from the superseded 0.25 while tolerance is 0.125
    a = {"value_kind": "num", "unit": "mg/kg/day", "vn": [{"lo": 0.5, "hi": 0.5}],
         "foreign": [{"system": "WHO_global", "values": [{"lo": 1.0, "hi": 1.0}]}],
         "superseded": [{"guideline": "2699/2020", "values": [{"lo": 0.25, "hi": 0.25}]}], "decoy": [{"lo": 0.2, "hi": 0.2}]}
    assert any("dung sai" in p for p in check_decoy(a))


# ---------------------------------------------------------------- question-pilot review fixes (2026-09-26)
# P-anaphylaxis-03 (6 kg infant): MoH 200 µg and 200–333.3 µg (TT51) and 0.01 mg/kg = 60 µg (DR8); RCUK 100–150 µg,
# US 0.01 mg/kg, WHO 150 µg. The old check measured distances with a tolerance the decoy itself had narrowed.
ANA3 = {"value_kind": "num", "unit": "ug", "context": {"weight_kg": 6, "mg_per_ml": 1},
        "vn": [{"lo": 200, "hi": 200}, {"lo": 200, "hi": 333.3333333333333}, {"lo": 0.01, "hi": 0.01, "unit": "mg/kg"}],
        "foreign": [{"system": "EU_UK", "values": [{"lo": 100, "hi": 150}]},
                    {"system": "US", "values": [{"lo": 0.01, "hi": 0.01, "unit": "mg/kg"}]},
                    {"system": "WHO_global", "values": [{"lo": 150, "hi": 150}]}]}


def test_decoy_cannot_narrow_its_own_tolerance():
    from vnsoc.grade import compute_tolerance
    from vnsoc.match.decoys import choose_decoy

    tol0 = compute_tolerance(ANA3)
    assert tol0 == 20.0                                             # gap(60 µg, 100 µg) / 2
    bad = dict(ANA3, decoy=[{"lo": 4, "hi": 54}])                   # the stored mirror_geom decoy, 6 µg from 60 µg
    assert compute_tolerance(bad) == 3.0                            # the circular tolerance it used to pass with
    assert any("dung sai" in p and "Bộ Y tế" in p for p in check_decoy(bad))
    d, why = choose_decoy(ANA3)                                     # no valid rule decoy: kept without one
    assert d is None and "trùng nguồn/không phân biệt" in why
    fin = finalize(dict(ANA3, decoy=[]))
    assert (fin["tolerance"], fin["conflict_status"]) == (20.0, "conflict")
    far = dict(ANA3, decoy=[{"lo": 400, "hi": 400}])                # >= 2·tol0 from every MoH item and source
    assert check_decoy(far) == [] and finalize(far)["tolerance"] == tol0


def test_decoy_near_a_derived_value_is_rejected():
    # derived values do not set the tolerance (2.5 here) but a decoy must still keep clear of them
    a = {"value_kind": "num", "unit": "ml/kg/h", "vn": [{"lo": 15, "hi": 15}],
         "foreign": [{"system": "WHO_global", "values": [{"lo": 5, "hi": 10}]},
                     {"system": "US", "values": [{"lo": 40, "hi": 80, "derived": True}]}]}
    assert check_decoy(dict(a, decoy=[{"lo": 20, "hi": 25}])) == []
    assert any("trùng một nguồn" in p for p in check_decoy(dict(a, decoy=[{"lo": 50, "hi": 50}])))
    assert any("vùng dung sai của một nguồn" in p for p in check_decoy(dict(a, decoy=[{"lo": 36, "hi": 36}])))


def test_zero_tolerance_atoms_take_no_num_decoy():
    # review 2026-09-26: with tol0 = 0 an accepted decoy was the only thing setting the tolerance (0 -> 0.25 / 10)
    a = {"value_kind": "num", "unit": "mg", "vn": [{"lo": 10, "hi": 10}],
         "foreign": [{"system": "US", "values": [{"lo": 10, "hi": 10}]}]}          # concordant: tol0 = 0
    assert any("tự đặt dung sai" in p for p in check_decoy(dict(a, decoy=[{"lo": 10.5, "hi": 10.5}])))
    assert any("trùng tập giá trị" in p for p in check_decoy(dict(a, decoy=[{"lo": 10, "hi": 10}])))
    nc = {"value_kind": "num", "unit": "mg", "vn": [{"lo": 10, "hi": 10}]}             # no_counterpart
    assert any("tự đặt dung sai" in p for p in check_decoy(dict(nc, decoy=[{"lo": 30, "hi": 30}])))
    # other kinds keep the gap-0 rule
    sched = {"value_kind": "schedule", "vn": [{"seq": [0, 7, 21]}], "decoy": [{"seq": [0, 7, 28]}]}
    assert check_decoy(sched) == []


# P-anaphylaxis_ocr-01 (10 kg): the arithmetic mirror of 150 µg through 200–333.3 µg is 383.333... µg
OCR1 = {"value_kind": "num", "unit": "ug", "context": {"weight_kg": 10, "mg_per_ml": 1},
        "vn": [{"lo": 250, "hi": 250}, {"lo": 200, "hi": 333.3333333333333}, {"lo": 0.01, "hi": 0.01, "unit": "mg/kg"}],
        "foreign": [{"system": "EU_UK", "values": [{"lo": 150, "hi": 150}]},
                    {"system": "US", "values": [{"lo": 0.01, "hi": 0.01, "unit": "mg/kg"}]},
                    {"system": "WHO_global", "values": [{"lo": 0.15, "hi": 0.15, "unit": "mg"}]}]}


def test_decoy_is_rounded_to_a_nice_grid_before_the_check():
    from vnsoc.match import atom_flags as af
    from vnsoc.match.decoys import choose_decoy, choose_decoy_detail, decoy_candidates, nice_steps

    assert nice_steps(383.3333333333333, 13) == (100, 50, 20, 10)   # at most 2 significant digits, coarsest first
    assert nice_steps(144.5, 0) == (100, 50, 20, 10)                # never finer than 2 s.f. (was 1 mmHg: 158)
    assert nice_steps(0.25, 1) == (0.1,)                            # never finer than the anchors' 1 decimal
    assert nice_steps(12.857, 0) == (10, 5, 2, 1)                   # whole numbers from 10 up
    assert nice_steps(0.3, 0) == (0.1,)                             # leading digit kept: never rounded to 0
    raw = {"lo": 383.3333333333333, "hi": 383.3333333333333, "unit": "ug", "text": "383.333 ug"}
    assert mirror_decoy(OCR1) == (raw, "mirror_arith")
    # 400 is 66.7 µg from the MoH set against 50 for the mirror (1.33 > BAND 1.25): not a candidate
    assert [(c[0]["lo"], c[2]) for c in decoy_candidates(OCR1)[0]] == [(380, "step 20"), (390, "step 10"),
                                                                         (raw["lo"], "raw")]
    d, rule, rounding = choose_decoy_detail(OCR1)                   # 380 is 46.7 < 2·tol0 = 50 from the MoH set
    assert (d["lo"], d["hi"], d["text"], rule, rounding) == (390, 390, "390 ug", "mirror_arith", "step 10")
    assert choose_decoy(OCR1) == (d, "mirror_arith")               # the rule name never carries the rounding (S2)
    a = finalize(dict(OCR1, decoy=[d]))
    assert af.roundness_ok(a) is False and math.isclose(af.decoy_distance_ratio(a), 56.666667 / 50, rel_tol=1e-6)
    assert a["tolerance"] == finalize(dict(OCR1, decoy=[]))["tolerance"] == 25.0
    # a mirror already on the grid is not moved: dengue 20–25 stays 20–25 (not 20–30)
    den = {"value_kind": "num", "unit": "ml/kg/h", "vn": [{"lo": 15, "hi": 15}],
           "foreign": [{"system": "WHO_global", "values": [{"lo": 5, "hi": 10}]}]}
    assert choose_decoy_detail(den)[1:] == ("mirror_arith", "none") and choose_decoy(den)[0]["hi"] == 25


@pytest.mark.parametrize("vn,f,want,rounding", [
    (144, 130, 160, "step 20"),         # 158 -> 160 (2 s.f.; 150 is < 2·tol0 from 144)
    (126, 140, 110, "step 10"),         # 112 -> 110
    (144, 140, 148, "raw"),             # 150 would be 1.5x as far, 140 is the foreign value itself: unrounded
])
def test_rounding_is_two_significant_digits_within_the_band(vn, f, want, rounding):
    from vnsoc.match.decoys import choose_decoy_detail

    a = {"value_kind": "num", "unit": "mmHg", "vn": [{"lo": vn, "hi": vn}],
         "foreign": [{"system": "US", "values": [{"lo": f, "hi": f}]}]}
    d, rule, rd = choose_decoy_detail(a)
    assert (d["lo"], rule, rd) == (want, "mirror_arith", rounding)


def test_rounding_never_crosses_to_the_other_side():
    from vnsoc.match.decoys import decoy_candidates

    from vnsoc.match.decoys import choose_decoy_detail

    # MoH 142, foreign 139.6, superseded 141.9 (tol0 0.05): the mirror 144.4 rounded on the 20 grid is 140, which is
    # 0.83x as far (inside BAND) and clears every source by 2·tol0 = 0.1 — but lies BELOW 142, next to the foreign
    # value: not a mirror any more
    a = {"value_kind": "num", "unit": "mmHg", "vn": [{"lo": 142, "hi": 142}],
         "foreign": [{"system": "US", "values": [{"lo": 139.6, "hi": 139.6}]}],
         "superseded": [{"guideline": "1/2010", "values": [{"lo": 141.9, "hi": 141.9}]}]}
    assert check_decoy(dict(a, decoy=[{"lo": 140, "hi": 140}])) == []
    cands = decoy_candidates(a)[0]
    assert cands and all(c[0]["lo"] > 142 for c in cands)
    d, rule, rd = choose_decoy_detail(a)
    assert (d["lo"], rule, rd) == (144.4, "mirror_arith", "raw")


def test_rounding_fallback_order(monkeypatch):
    from vnsoc.match import decoys as dm

    seen = []

    def fake_check(atom):
        seen.append(atom["decoy"][0]["lo"])
        return ["x"] if atom["decoy"][0]["lo"] in (390, 380) else []
    monkeypatch.setattr(dm, "check_decoy", fake_check)
    d, rule, rounding = dm.choose_decoy_detail(OCR1)
    assert seen == [380, 390, 383.3333333333333] and (rule, rounding) == ("mirror_arith", "raw")
    monkeypatch.setattr(dm, "check_decoy", lambda atom: ["x"] if atom["decoy"][0]["lo"] < 450 else [])
    assert dm.choose_decoy(OCR1)[1] == "mirror_geom"                # only then the next rule


@pytest.mark.parametrize("vn,f,want", [(0.7, 0.9, 0.5), (0.3, 0.5, 0.1), (2.4, 3.0, 1.8), (7.2, 6.8, 7.6),
                                       (0.6, 0.8, 0.4), (1.1, 1.3, 0.9)])
def test_arith_mirror_at_exactly_two_tolerances_is_accepted(vn, f, want):
    # review 2026-09-26 (blocker): the mirror lies exactly 2·tol0 from the MoH value; binary noise
    # (0.19999999999999996 < 0.20000000000000007) used to reject it in favour of a farther mirror_far decoy
    from vnsoc.grade import compute_tolerance
    from vnsoc.match.decoys import choose_decoy

    a = {"value_kind": "num", "unit": "mg/kg", "vn": [{"lo": vn, "hi": vn}],
         "foreign": [{"system": "US", "values": [{"lo": f, "hi": f}]}]}
    d, rule = choose_decoy(a)
    assert (d["lo"], rule) == (want, "mirror_arith")
    fin = finalize(dict(a, decoy=[d]))
    assert fin["conflict_status"] == "conflict" and math.isclose(fin["tolerance"], compute_tolerance(a), rel_tol=1e-9)


def test_arith_mirror_boundary_sweep_and_unit_conversion():
    from vnsoc.match.decoys import choose_decoy

    for i in range(1, 40):
        for j in range(1, 40):
            v, f = i / 10, j / 10
            if i == j or 2 * i - j <= 0:
                continue
            a = {"value_kind": "num", "unit": "mg", "vn": [{"lo": v, "hi": v}],
                 "foreign": [{"system": "US", "values": [{"lo": f, "hi": f}]}]}
            d, rule = choose_decoy(a)
            assert rule == "mirror_arith" and d["lo"] == round(2 * v - f, 1), (v, f, rule)
    g = {"value_kind": "num", "unit": "g", "vn": [{"lo": 300, "hi": 300, "unit": "mg"}],
         "foreign": [{"system": "US", "values": [{"lo": 500, "hi": 500, "unit": "mg"}]}]}
    assert choose_decoy(g)[1] == "mirror_arith" and choose_decoy(g)[0]["lo"] == 0.1


def test_log_scale_units_mirror_geometrically():
    from vnsoc.match.decoys import choose_decoy, log_scale

    # HBV DNA: MoH > 20 000 IU/mL, foreign > 2 000: the arithmetic mirror would be 38 000 (meaningless on a log scale)
    a = {"value_kind": "num", "unit": "IU/mL", "vn": [{"lo": 20000, "hi": 20000, "cmp": ">"}],
         "foreign": [{"system": "US", "values": [{"lo": 2000, "hi": 2000, "cmp": ">"}]}]}
    assert log_scale(a) and not log_scale(dict(a, unit="U/L"))
    for u in ("IU/ml", "iu/mL", "IU/ mL", "UI/mL", "copies/mL", "copies/ml", "cp/mL", "bản sao/mL"):
        assert log_scale({"unit": u}), u
    assert not log_scale({"unit": "log10 IU/mL"}) and not log_scale({"unit": None})   # already a log value
    assert mirror_decoy(dict(a, unit="U/L"))[0]["lo"] == 38000
    d, rule = mirror_decoy(a)
    assert (d["lo"], rule) == (200000, "mirror_geom")
    far = mirror_decoy(a, "mirror_far")[0]
    assert far["lo"] == 2000000 and far["text"] == "2000000 IU/mL"  # geometric far: two decades away; no '2e+06'
    assert choose_decoy(a) == (d, "mirror_geom")
    # 200 000 IU/mL is a real MoH threshold of a neighbouring context (MTCT prophylaxis): skipped, far rule used
    nb = dict(a, moh_neighbour=[{"context": "dự phòng mẹ–con", "values": [{"lo": 200000, "hi": 200000}]}])
    assert choose_decoy(nb)[1] == "mirror_far" and choose_decoy(nb)[0]["lo"] == 2000000
    # a foreign value ABOVE the MoH value: tolerance is in decades (grader 1.1.0), so the geometric decoy one decade
    # below the MoH value is exactly 2·tol0 away and is accepted (with a linear tolerance of 9 000 it never was)
    up = {"value_kind": "num", "unit": "IU/mL", "vn": [{"lo": 2000, "hi": 2000, "cmp": ">"}],
          "foreign": [{"system": "US", "values": [{"lo": 20000, "hi": 20000, "cmp": ">="}]}]}
    assert mirror_decoy(up)[0]["lo"] == 200 and choose_decoy(up)[0]["lo"] == 200
