"""Decoys are generated by a fixed rule (num/bp) and checked (all kinds). Values are TEST FIXTURES, not data."""
from vnsoc.match.decoys import check_decoy, finalize, mirror_decoy


def test_mirror_num_dengue():
    a = {"value_kind": "num", "unit": "ml/kg/h", "vn": [{"lo": 15, "hi": 15}],
         "foreign": [{"system": "WHO_global", "values": [{"lo": 5, "hi": 10}]}]}
    d, rule = mirror_decoy(a)
    assert rule == "mirror_arith" and (d["lo"], d["hi"]) == (20, 25)
    a["decoy"] = [d]
    assert check_decoy(a) == [] and finalize(a)["conflict_status"] == "conflict"


def test_mirror_geom_when_arith_nonpositive():
    a = {"value_kind": "num", "unit": "U/L", "vn": [{"lo": 30, "hi": 30}],
         "foreign": [{"system": "US", "values": [{"lo": 70, "hi": 70}]}]}
    d, rule = mirror_decoy(a)
    assert rule == "mirror_geom" and d["lo"] == d["hi"] and 12 < d["lo"] < 13.5


def test_mirror_bp():
    a = {"value_kind": "bp", "vn": [{"sys": 140, "dia": 90}],
         "foreign": [{"system": "US", "values": [{"sys": 130, "dia": 80}]}, {"system": "EU_UK", "values": [{"sys": 140, "dia": 90}]}]}
    d, _ = mirror_decoy(a)
    assert (d["sys"], d["dia"]) == (150, 100)


def test_check_decoy_rejects_source_values():
    a = {"value_kind": "schedule", "vn": [{"seq": [0, 3, 7, 14, 28]}],
         "foreign": [{"system": "US", "values": [{"seq": [0, 3, 7, 14]}]}], "decoy": [{"seq": [0, 3, 7, 14]}]}
    assert any("nguồn" in p for p in check_decoy(a))
    a["decoy"] = [{"seq": [0, 3, 7, 21]}]
    assert check_decoy(a) == []
    assert mirror_decoy(a)[0] is None


def test_no_conflict_no_decoy():
    a = {"value_kind": "num", "unit": "mg", "vn": [{"lo": 0.5, "hi": 1.0}],
         "foreign": [{"system": "EU_UK", "values": [{"lo": 0.5, "hi": 0.5}]}]}
    assert mirror_decoy(a) == (None, "không có giá trị nước ngoài xung đột")
    assert finalize(a)["conflict_status"] == "concordant"


def test_mirror_converts_units_first():
    # found by the anaphylaxis pilot agent: foreign 0.01 mg/kg vs MoH µg for a 10 kg child
    a = {"value_kind": "num", "unit": "ug", "context": {"weight_kg": 10, "mg_per_ml": 1},
         "vn": [{"lo": 250, "hi": 250}], "foreign": [{"system": "OTHER", "values": [{"lo": 0.01, "hi": 0.01, "unit": "mg/kg"}]}]}
    d, rule = mirror_decoy(a)
    assert rule == "mirror_arith" and (d["lo"], d["hi"]) == (400, 400) and d["unit"] == "ug"   # 250 + (250 - 100)


def test_choose_decoy_skips_values_of_older_foreign_versions():
    from vnsoc.match.decoys import choose_decoy

    # target SBP >= 65 y: MoH 130-139; ACC/AHA < 130 (as 120-129); JNC8 2014 < 150 recorded as an older US version
    a = {"value_kind": "num", "unit": "mmHg", "vn": [{"lo": 130, "hi": 139}],
         "foreign": [{"system": "US", "values": [{"lo": 120, "hi": 129}]},
                     {"system": "US", "values": [{"lo": 140, "hi": 149}]}]}
    d, rule = mirror_decoy(a)
    assert (d["lo"], d["hi"]) == (140, 149) and check_decoy(dict(a, decoy=[d]))      # arith lands on JNC8-like value
    d2, rule2 = choose_decoy(a)
    assert rule2 in ("mirror_geom", "mirror_far") and check_decoy(dict(a, decoy=[d2])) == []


def test_bp_far_rule():
    a = {"value_kind": "bp", "vn": [{"sys": 140, "dia": 90}], "foreign": [{"system": "US", "values": [{"sys": 130, "dia": 80}]}]}
    assert mirror_decoy(a, "mirror_far")[0]["sys"] == 160


def test_check_decoy_blames_decoy_only_when_it_causes_indistinguishable():
    # MoH ULN 30; US 35 equals the superseded MoH value 35 -> indistinguishable before any decoy
    a = {"value_kind": "num", "unit": "U/L", "vn": [{"lo": 30, "hi": 30}],
         "foreign": [{"system": "US", "values": [{"lo": 35, "hi": 35}]}],
         "superseded": [{"guideline": "3310/2019", "values": [{"lo": 35, "hi": 35}]}], "decoy": [{"lo": 25, "hi": 25}]}
    assert finalize(dict(a, decoy=[]))["conflict_status"] == "indistinguishable"
    assert check_decoy(a) == []


def test_decoy_inside_tolerance_of_a_source_is_rejected():
    # malaria OCR audit: decoy 0.2 sits 0.05 from the superseded 0.25 while tolerance is 0.125
    a = {"value_kind": "num", "unit": "mg/kg/day", "vn": [{"lo": 0.5, "hi": 0.5}],
         "foreign": [{"system": "WHO_global", "values": [{"lo": 1.0, "hi": 1.0}]}],
         "superseded": [{"guideline": "2699/2020", "values": [{"lo": 0.25, "hi": 0.25}]}], "decoy": [{"lo": 0.2, "hi": 0.2}]}
    assert any("dung sai" in p for p in check_decoy(a))
