"""Operating characteristics of the pre-registered confirmatory analyses on SIMULATED data (T2.10; revised
2026-09-26 after the preregistration review, review/prereg/response.md).

Runs vnsoc.analysis.confirmatory on data from simulate_study() under null and alternative scenarios, at the REGISTERED
bootstrap size (B = 10,000) and with the REGISTERED estimators, and writes every number to
prereg/analysis_plan/operating_characteristics.json (script output, never typed by hand); the table between the OC
markers in prereg/analysis_plan/README.md is regenerated from the same numbers.

Registered checks (rev-methods id 1, rev-editor id 2): in every null scenario the rejection rate of the registered
rule is at most 0.025 + 2 MCSE (MCSE = sqrt(0.025 * 0.975 / reps)) for H1, H4, the H3 least-favourable nulls and the
Holm family; H1 power at the protocol effect (30% vs 5%) is at least 0.95. The rules compared:
  H1  registered 'conservative' (BCa AND expanded BCa AND cluster jackknife-t AND wild cluster bootstrap-t),
      the protocol's textbook BCa alone, and the three-interval rule without the wild bootstrap;
  H4  registered (Mantel-Haenszel RR by model x language, value-stating answers, labels 3-5, guideline clusters,
      'conservative'), the same with BCa alone, and the pre-review estimator (crude pooled RR, loss W = labels 3-6).
Null scenarios keep abstentions concentrated in the disagreement group, model-specific disagreement shares and base
risks (Simpson confounding), k_i = 2 targets on 30% of conflict atoms and 5% decoy-less conflict atoms.

  cd "/d/phan chau trinh _ y khoa" && PYTHONUTF8=1 .venv/bin/python prereg/analysis_plan/simulate_operating_characteristics.py
  options: --workers N (default min(11, CPUs)), --n-boot B (default 10000 = registered), --quick (x0.1 replicates,
  no file writes), --render-only (re-render the README table and the registration summary from the JSON)
"""
from __future__ import annotations

import argparse
import json
import math
import os
import platform
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import scipy  # noqa: E402

from vnsoc.analysis import confirmatory as cf  # noqa: E402

HERE = Path(__file__).resolve().parent
OUT_JSON = HERE / "operating_characteristics.json"
README = HERE / "README.md"
PREREG = HERE.parent / "osf_preregistration.md"
BEGIN, END = "<!-- OC:BEGIN (generated by simulate_operating_characteristics.py; do not edit by hand) -->", \
    "<!-- OC:END -->"
SBEGIN, SEND = "<!-- OCSUM:BEGIN -->", "<!-- OCSUM:END -->"
BASE_SEED = 20261001
ALPHA = cf.ALPHA_ONE_SIDED

MODEST = {"pi_foreign": 0.10, "pi_decoy": 0.05, "h2_en_mult": 1.2, "a3_rate": 0.08, "h4_rr": 2.5}
UNEQ = {"family_size_sigma": 1.0}            # lognormal family sizes (sd of log size 1.0; largest ~5-10x median)
LFC = {**cf.NULL_EFFECT, "a3_rate": [0.30, 0.05, 0.05, 0.05]}
SCENARIOS = [
    # name, n_families, atoms_per_family, effect overrides, replicates, kind, role
    ("null_40x10", 40, 10, cf.NULL_EFFECT, 2000, "null", "global null, planning design (400 conflict atoms, 40 families)"),
    ("null_25x16", 25, 16, cf.NULL_EFFECT, 2000, "null", "global null, minimum design (DR2: 400 atoms, 25 families)"),
    ("null_25x16_uneq", 25, 16, {**cf.NULL_EFFECT, **UNEQ}, 2000, "null",
     "global null, 25 families with lognormal sizes (mean 16)"),
    ("null_12x10", 12, 10, cf.NULL_EFFECT, 2000, "null", "global null, < 20 families (small-sample path)"),
    ("h3lfc_40x10", 40, 10, LFC, 2000, "null",
     "H3 least-favourable null: one model at 30%, three exactly at the 5% margin (other nulls as global)"),
    ("h3lfc_25x16_uneq", 25, 16, {**LFC, **UNEQ}, 2000, "null", "H3 least-favourable null, unequal families"),
    ("alt_40x10", 40, 10, {}, 400, "alt", "protocol effect: pi_f 0.30 vs pi_d 0.05; H2 x1.5; H3 10%; H4 RR 3"),
    ("alt_25x16", 25, 16, {}, 300, "alt", "protocol effect, minimum design"),
    ("alt_25x16_uneq", 25, 16, UNEQ, 300, "alt", "protocol effect, unequal families"),
    ("alt_12x10", 12, 10, {}, 300, "alt", "protocol effect, < 20 families"),
    ("modest_40x10", 40, 10, MODEST, 300, "alt", "modest effect: pi_f 0.10 vs 0.05; H2 x1.2; H3 8%; H4 RR 2.5"),
]
H3_NULLS = ("h3lfc_40x10", "h3lfc_25x16_uneq")
H1_NULLS = ("null_40x10", "null_25x16", "null_25x16_uneq", "null_12x10") + H3_NULLS   # H1, H2, H4 nulls hold in all
H4_NULLS = H1_NULLS
H1_ALTS = ("alt_40x10", "alt_25x16", "alt_25x16_uneq", "alt_12x10")


def one_rep(job: tuple) -> dict:
    name, n_fam, apf, effect, seed, n_boot = job
    df = cf.simulate_study(seed, n_families=n_fam, atoms_per_family=apf, effect=effect)
    h1 = cf.h1_delta(df, n_boot=n_boot, seed=seed)
    h2 = cf.h2_mcnemar_clustered(df, n_boot=200, seed=seed)       # effect-size CI not used for decisions here
    h3 = cf.h3_per_model(df)
    h4 = cf.h4_risk_ratio(df, n_boot=n_boot, seed=seed)
    h4c = cf.h4_risk_ratio(df, n_boot=n_boot, seed=seed, loss="W", estimator="crude")
    ho = cf.holm({"H2": h2["p_one_sided"], "H3": h3["p_pc"], "H4": h4["p_one_sided"]})
    try:
        rq = cf.certified_rq3(df, model="sim_m3")                  # one model, Vietnamese, as registered
    except ValueError:                                             # a group absent from the reference split
        rq = None
    v1, v4 = h1["variants"], h4["variants"]
    lb = math.log(cf.H4_RR_BOUND)
    return {
        "h1_registered": h1["confirmed"],
        "h1_bca_only": (v1["bca"]["lo"] > 0) if "bca" in v1 else (v1["jackknife_t"]["lo"] > 0),
        "h1_iu3": all(v["lo"] > 0 for v in v1.values()),
        "h1_wild_only": h1["wild_cluster"]["p_one_sided"] <= ALPHA,
        "h1_upper_below0": h1["ci_hi"] < 0, "h1_delta": h1["delta"], "h1_method": h1["method"],
        "h2_reject": h2["p_one_sided"] <= ALPHA, "h2_test": h2["test"],
        "h3_reject": h3["p_pc"] <= ALPHA, "h3_models_lb_above": h3["n_models_lb_above_margin"],
        "h4_registered": h4["ci_lo"] > cf.H4_RR_BOUND,
        "h4_bca_only": (v4["bca"]["lo"] > cf.H4_RR_BOUND) if "bca" in v4 else (v4["jackknife_t"]["lo"] > cf.H4_RR_BOUND),
        "h4_pre_review_crude_W": h4c["ci_lo"] > cf.H4_RR_BOUND, "h4_log_rr": h4["log_rr"],
        "h4_log_rr_crude_W": h4c["log_rr"] if np.isfinite(h4c["log_rr"]) else lb,
        "holm_any": any(v["reject"] for v in ho.values()),
        "holm_h2": ho["H2"]["reject"], "holm_h3": ho["H3"]["reject"], "holm_h4": ho["H4"]["reject"],
        "rq3_bound_violation_pool": np.nan if rq is None else rq["any_bound_violation_pool"],
        "rq3_ltt_violation_pool": np.nan if rq is None else any(v["violation_pool"] for v in rq["ltt"].values()),
        "rq3_disagree_cov": np.nan if rq is None else rq["ltt"]["disagree"]["coverage_test"],
        "rq3_self_abstention": np.nan if rq is None else rq["self_abstention_rate"],
    }


def rate(x) -> dict | None:
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    if len(x) == 0:
        return None
    p = float(x.mean())
    return {"rate": p, "mcse": math.sqrt(p * (1 - p) / len(x)), "n": int(len(x))}


KEYS = ["h1_registered", "h1_bca_only", "h1_iu3", "h1_wild_only", "h1_upper_below0", "h2_reject", "h3_reject",
        "h4_registered", "h4_bca_only", "h4_pre_review_crude_W", "holm_any", "holm_h2", "holm_h3", "holm_h4",
        "rq3_bound_violation_pool", "rq3_ltt_violation_pool"]


def summarize(rows: list[dict]) -> dict:
    df = pd.DataFrame(rows)
    out = {k: rate(df[k]) for k in KEYS}
    out["h1_delta_mean"] = float(df["h1_delta"].mean())
    out["h1_delta_sd"] = float(df["h1_delta"].std())
    out["h4_rr_geomean"] = float(np.exp(df["h4_log_rr"].mean()))
    out["h4_rr_crude_W_geomean"] = float(np.exp(df["h4_log_rr_crude_W"].mean()))
    out["h1_methods"] = df["h1_method"].value_counts().to_dict()
    out["h2_tests"] = df["h2_test"].value_counts().to_dict()
    out["h3_models_lb_above_mean"] = float(df["h3_models_lb_above"].mean())
    out["rq3_disagree_coverage_mean"] = float(df["rq3_disagree_cov"].mean())
    out["rq3_self_abstention_mean"] = float(df["rq3_self_abstention"].mean())
    return out


def size_limit(reps: int) -> float:
    return ALPHA + 2 * math.sqrt(ALPHA * (1 - ALPHA) / reps)


def checks_for(s: dict) -> dict:
    def get(n: str, k: str) -> float:
        return s[n]["results"][k]["rate"]

    def size(key: str, names) -> dict:
        det = ", ".join(f"{n} {get(n, key):.4f} (limit {size_limit(s[n]['reps']):.4f})" for n in names)
        return {"pass": all(get(n, key) <= size_limit(s[n]["reps"]) for n in names), "detail": det}

    return {
        "h1_size_registered": size("h1_registered", H1_NULLS),
        "h1_power_registered_ge_0.95": {"pass": all(get(n, "h1_registered") >= 0.95 for n in H1_ALTS),
                                        "detail": ", ".join(f"{n} {get(n, 'h1_registered'):.3f}" for n in H1_ALTS)},
        "h4_size_registered": size("h4_registered", H4_NULLS),
        "h3_size_lfc": size("h3_reject", H3_NULLS),
        "holm_fwer_registered": size("holm_any", H1_NULLS),
        "h2_size": size("h2_reject", H1_NULLS),
        "(for comparison, not registered) h1_size_bca_only": size("h1_bca_only", H1_NULLS),
        "(for comparison, not registered) h4_size_pre_review_crude_W": size("h4_pre_review_crude_W", H4_NULLS),
    }


def fmt(r: dict | None) -> str:
    return "—" if r is None else f"{r['rate']:.3f} ({r['mcse']:.3f})"


def render(res: dict) -> str:
    sc = res["scenarios"]
    L = [BEGIN, "",
         f"Generated {res['generated_at']} by `simulate_operating_characteristics.py` from "
         f"`operating_characteristics.json`. B = {res['settings']['n_boot']} bootstrap resamples (the registered "
         f"size) for H1 and H4; one-sided decision level {res['settings']['alpha_one_sided']:.3f}; Monte Carlo "
         "standard errors in brackets. Entries are rejection rates: type I error under a null scenario, power under "
         "an alternative. Registered rules: H1 = BCa ∧ expanded BCa ∧ cluster jackknife-t ∧ wild cluster "
         "bootstrap-t; H4 = Mantel–Haenszel RR (model × language) on value-stating answers, loss = labels 3–5, "
         "guideline clusters, BCa ∧ expanded BCa ∧ jackknife-t.",
         "", "| Scenario | Reps | H1 registered | H1 BCa alone | H2 | H3 (partial conj.) | H4 registered | "
             "Holm: any of H2–H4 | RQ3 (a) some U_gk exceeded (sim_m3, VI) | H1 interval path |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for name, s in sc.items():
        r = s["results"]
        L.append(f"| `{name}`: {s['role']} | {s['reps']} | {fmt(r['h1_registered'])} | {fmt(r['h1_bca_only'])} | "
                 f"{fmt(r['h2_reject'])} | {fmt(r['h3_reject'])} | {fmt(r['h4_registered'])} | "
                 f"{fmt(r['holm_any'])} | {fmt(r['rq3_bound_violation_pool'])} | "
                 f"{', '.join(f'{k}: {v}' for k, v in r['h1_methods'].items())} |")
    L += ["", "Components and the pre-review H4 estimator (same replicates). `IU3` = BCa ∧ expanded BCa ∧ "
              "jackknife-t (the rule proposed by the methods reviewer); `wild` = wild cluster restricted bootstrap-t "
              "alone; `crude W` = crude pooled RR with self-abstentions counted as errors (the estimator registered "
              "before the review), with the geometric mean of its RR estimate against the true within-stratum RR.",
          "", "| Scenario | H1 IU3 | H1 wild | H4 BCa alone | H4 crude W (reject) | geo-mean RR: registered / crude W |",
          "|---|---|---|---|---|---|"]
    for name, s in sc.items():
        r = s["results"]
        L.append(f"| `{name}` | {fmt(r['h1_iu3'])} | {fmt(r['h1_wild_only'])} | {fmt(r['h4_bca_only'])} | "
                 f"{fmt(r['h4_pre_review_crude_W'])} | {r['h4_rr_geomean']:.2f} / {r['h4_rr_crude_W_geomean']:.2f} |")
    L += ["", "Checks (size limit = 0.025 + 2·MCSE at the scenario's replicate count):", ""]
    for k, v in res["checks"].items():
        L.append(f"- `{k}`: {'PASS' if v['pass'] else 'FAIL'} ({v['detail']})")
    L += ["", f"Run time: {res['runtime_s']:.0f} s with {res['settings']['workers']} worker processes.", "", END]
    return "\n".join(L)


def render_summary(res: dict) -> str:
    """Short summary for the registration (Section 3.3), generated from the same JSON."""
    sc, ch = res["scenarios"], res["checks"]

    def r(n, k):
        return sc[n]["results"][k]["rate"]

    def worst(k, names):
        n = max(names, key=lambda x: r(x, k))
        return f"{r(n, k):.3f} (`{n}`, limit {size_limit(sc[n]['reps']):.3f})"

    reg = [k for k in ch if not k.startswith("(")]
    L = [SBEGIN, "",
         f"*Generated {res['generated_at']} from `operating_characteristics.json` (B = {res['settings']['n_boot']}; "
         f"{sum(s['reps'] for s in sc.values())} simulated studies).* Largest rejection rate under a null: "
         f"H1 registered rule {worst('h1_registered', H1_NULLS)}; H1 with the protocol's BCa alone "
         f"{worst('h1_bca_only', H1_NULLS)}; H1 with BCa, expanded BCa and jackknife-t but no wild bootstrap "
         f"{worst('h1_iu3', H1_NULLS)}; H4 registered {worst('h4_registered', H4_NULLS)}; H4 with the first "
         f"draft's crude pooled RR and loss W {worst('h4_pre_review_crude_W', H4_NULLS)}; H3 at its least-favourable "
         f"null {worst('h3_reject', H3_NULLS)}; H2 {worst('h2_reject', H1_NULLS)}; Holm family "
         f"{worst('holm_any', H1_NULLS)}. Power of the registered rules at the protocol effect: H1 "
         + ", ".join(f"{r(n, 'h1_registered'):.3f} (`{n}`)" for n in H1_ALTS)
         + f"; H4 {r('alt_40x10', 'h4_registered'):.3f} and H3 {r('alt_40x10', 'h3_reject'):.3f} (`alt_40x10`); "
         f"at the modest effect (`modest_40x10`) H1 {r('modest_40x10', 'h1_registered'):.3f}, H3 "
         f"{r('modest_40x10', 'h3_reject'):.3f}, H4 {r('modest_40x10', 'h4_registered'):.3f}. Registered checks: "
         + ("all passed." if all(ch[k]["pass"] for k in reg) else
            "FAILED: " + ", ".join(k for k in reg if not ch[k]["pass"]) + "."),
         "", SEND]
    return "\n".join(L)


def _write_blocks(res: dict) -> None:
    for path, b, e, text in ((README, BEGIN, END, render(res)), (PREREG, SBEGIN, SEND, render_summary(res))):
        if path.exists():
            txt = path.read_text(encoding="utf-8")
            i, j = txt.find(b[:12]), txt.find(e)
            if i >= 0 and j > i:
                path.write_text(txt[:i] + text + txt[j + len(e):], encoding="utf-8", newline="\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=min(11, os.cpu_count() or 1))
    ap.add_argument("--n-boot", type=int, default=cf.N_BOOT)
    ap.add_argument("--quick", action="store_true", help="10%% of the replicates, writes nothing")
    ap.add_argument("--render-only", action="store_true", help="re-render README/prereg blocks from the JSON")
    a = ap.parse_args(argv)
    if a.render_only:
        res = json.loads(OUT_JSON.read_text(encoding="utf-8"))
        res["checks"] = checks_for(res["scenarios"])                # same simulated data, current check list
        OUT_JSON.write_text(json.dumps(cf._py(res), ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")
        _write_blocks(res)
        print("rendered README §6 and prereg §3.3 from", OUT_JSON.name)
        return 0
    t0 = time.time()
    res = {"generated_by": "prereg/analysis_plan/simulate_operating_characteristics.py",
           "generated_at": datetime.now().isoformat(timespec="seconds"),
           "versions": {"python": platform.python_version(), "numpy": np.__version__, "scipy": scipy.__version__,
                        "pandas": pd.__version__},
           "settings": {"n_boot": a.n_boot, "alpha_one_sided": ALPHA, "base_seed": BASE_SEED, "workers": a.workers,
                        "models": 4, "default_effect": cf.DEFAULT_EFFECT, "null_effect": cf.NULL_EFFECT,
                        "modest_effect": MODEST, "unequal": UNEQ, "decision_rule": cf.PRIMARY_RULE,
                        "seed_rule": "seed = base_seed + 100000*scenario_index + replicate"},
           "scenarios": {}}
    for si, (name, nf, apf, eff, reps, kind, role) in enumerate(SCENARIOS):
        reps = max(20, reps // 10) if a.quick else reps
        jobs = [(name, nf, apf, eff, BASE_SEED + 100000 * si + r, a.n_boot) for r in range(reps)]
        t = time.time()
        if a.workers > 1:
            with ProcessPoolExecutor(max_workers=a.workers) as ex:
                rows = list(ex.map(one_rep, jobs, chunksize=max(1, reps // (4 * a.workers))))
        else:
            rows = [one_rep(j) for j in jobs]
        res["scenarios"][name] = {"role": role, "kind": kind, "n_families": nf, "atoms_per_family": apf,
                                  "effect": {**cf.DEFAULT_EFFECT, **eff}, "reps": reps,
                                  "results": summarize(rows), "runtime_s": time.time() - t}
        print(f"{name}: {reps} replicates, {time.time() - t:.0f}s", flush=True)
    res["checks"] = checks_for(res["scenarios"])
    res["runtime_s"] = time.time() - t0
    print(json.dumps(res["checks"], ensure_ascii=False, indent=1))
    if a.quick:
        return 0
    OUT_JSON.write_text(json.dumps(cf._py(res), ensure_ascii=False, indent=1) + "\n", encoding="utf-8", newline="\n")
    _write_blocks(json.loads(OUT_JSON.read_text(encoding="utf-8")))
    print(f"wrote {OUT_JSON.relative_to(ROOT)} ({res['runtime_s']:.0f}s)")
    reg = [k for k in res["checks"] if not k.startswith("(")]
    print("registered checks:", "PASS" if all(res["checks"][k]["pass"] for k in reg) else "FAIL (xem README §6)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
