"""Decoy values (proposal §1.2, §4.2): the chance-coincidence control for H1.

A decoy has the same kind and unit as the MoH value and lies about as far from it as the conflicting foreign value,
but belongs to no known source. For numeric and blood-pressure atoms the decoy is generated by a fixed rule so that
nobody chooses it after seeing model outputs (never chosen by hand; DECISIONS 2026-09-26):

  num  "mirror_arith": reflect the nearest conflicting foreign interval through the nearest MoH value
       (centre c_d = 2·c_vn − c_f, same width as the foreign interval); if that is ≤ 0, "mirror_geom":
       c_d = c_vn² / c_f (same ratio on the other side); "mirror_far" (3·c_vn − 2·c_f) is the last fallback.
       Log-scale quantities (log_scale: viral load in IU/mL or copies/mL, any spelling) are ALWAYS mirrored
       geometrically, in log space (bounds c_vn²/f.hi, c_vn²/f.lo; "mirror_far": c_vn³/f.hi², c_vn³/f.lo²), because
       an arithmetic reflection on a log scale has no clinical meaning (2·2000 − 20000 < 0; 2·20000 − 2000 = 38000).
       Values already recorded on a log scale ("log10 IU/mL") are mirrored arithmetically, which is the same thing.
       Rounding (decoy_candidates): a mirror whose ends are already on the 2-significant-digit grid is used as it is
       (rounding "none"). Otherwise it is rounded on the nice grid of nice_steps (10^e, 5·10^(e−1), 2·10^(e−1),
       10^(e−1), coarsest first), to the nearest grid point and then away from the MoH value; a rounded candidate is
       kept only if its distance from the MoH set is within BAND (0.8–1.25×) of the unrounded mirror's distance, so a
       rounded decoy stays about as far as the foreign value. The unrounded mirror ("raw") comes last.
  bp   "mirror_arith" per component: 2·vn − foreign ("mirror_far": 3·vn − 2·foreign); whole mmHg, not rounded.
The rule name never carries the rounding (a rounded arithmetic mirror is still "mirror_arith": the registered S2
set is decoy_rule == "mirror_arith"); choose_decoy_detail also returns the rounding (Atom.extraction.decoy_rounding).
For schedule / drugs / cat atoms the decoy is a real-looking alternative proposed by a person or agent;
`check_decoy` rejects it if it equals any recorded source value or makes the atom indistinguishable.

The decoy never sets the tolerance: check_decoy measures every distance with tol0 = the tolerance of the atom WITHOUT
its decoy, and an accepted num/bp decoy lies ≥ 2·tol0 from every MoH item and every recorded value, so the final
tolerance equals tol0 (up to binary rounding noise, see `below`). A num/bp atom with tol0 = 0 (no other value at a
finite, non-zero gap) takes no decoy: the decoy would be the only thing setting its tolerance.

`finalize(atom)` recomputes tolerance and conflict_status with vnsoc.grade (the single definition) — call it last.
"""
from __future__ import annotations

import math
from decimal import ROUND_CEILING, ROUND_FLOOR, ROUND_HALF_UP, Decimal

from vnsoc.grade import LOG_SCALE_UNITS, REL_TOL, _gap, below, compute_tolerance, conflict_status, log_scale  # noqa: F401

RULES = ("auto", "mirror_geom", "mirror_far")             # pre-specified order (choose_decoy)
BAND = (0.8, 1.25)       # rounded decoy distance / unrounded mirror distance from the MoH set (log-symmetric, ±25 %)



def _decimals(*xs: float) -> int:
    d = 0
    for x in xs:
        e = Decimal(str(float(x))).normalize().as_tuple().exponent
        d = max(d, -e if isinstance(e, int) and e < 0 else 0)
    return d


def fmt_num(x: float) -> str:
    """Up to 6 significant digits, never in exponent form (2000000, not 2e+06)."""
    s = f"{float(x):.6g}"
    return format(Decimal(s), "f") if "e" in s else s



def roundness(x: float) -> float:
    """Largest step s = m·10^j (m in {1, 2, 5}, -6 <= j <= 6) such that x is an integer multiple of s; 0 if none."""
    d = abs(Decimal(str(float(x))))
    if d == 0:
        return math.inf
    for j in range(6, -7, -1):
        for m in (5, 2, 1):
            s = Decimal(m) * (Decimal(10) ** j)
            if d % s == 0:
                return float(s)
    return 0.0


def _round_dir(x: float, step: float, mode: str) -> float:
    return float((Decimal(str(x)) / Decimal(str(step))).quantize(Decimal(1), rounding=mode) * Decimal(str(step)))


def round_to(x: float, step: float) -> float:
    """x rounded half-up to a multiple of step (decimal arithmetic: no binary noise such as 0.30000000000000004)."""
    return _round_dir(x, step, ROUND_HALF_UP)


def nice_steps(c: float, nd: int) -> tuple[float, ...]:
    """Pre-specified rounding grid for a decoy centred at c > 0, coarsest first: 10^e, 5·10^(e−1), 2·10^(e−1),
    10^(e−1) with e = floor(log10 c) — at most 2 significant digits — each never finer than the nd decimals of the
    anchor values as recorded (before unit conversion), whole numbers from 10 up, and never coarser than 10^e (the
    decoy keeps its leading digit and is never rounded to 0)."""
    e = math.floor(math.log10(c))
    top = float(Decimal(1).scaleb(e))
    floor_ = max(float(Decimal(1).scaleb(-nd)), 1.0 if c >= 10 else 0.0)
    out: list[float] = []
    for m, k in ((1, e), (5, e - 1), (2, e - 1), (1, e - 1)):
        s = min(max(float(Decimal(m).scaleb(k)), floor_), top)
        if s not in out:
            out.append(s)
    return tuple(out)


def in_atom_unit(item: dict, atom: dict):
    """A num ValueItem as nv.Num in the atom's unit (context: weight_kg, mg_per_ml, analyte...), or None."""
    from vnsoc import normalize_vi as nv

    unit = atom.get("unit")
    return nv.Num(float(item["lo"]), float(item["hi"]), item.get("unit") or unit).to(unit, atom.get("context") or {})


def num_item(lo: float, hi: float, unit: str | None) -> dict:
    text = fmt_num(lo) if lo == hi else f"{fmt_num(lo)}–{fmt_num(hi)}"
    return {"lo": lo, "hi": hi, "unit": unit, "text": f"{text} {unit or ''}".strip()}


def _conflicting(atom: dict) -> list[dict]:
    """Conflicting foreign items; items flagged derived=True (computed, not verbatim) never anchor a decoy."""
    vn = atom.get("vn") or []
    return [it for f in atom.get("foreign") or [] for it in f["values"]
            if not it.get("derived") and all(_gap(v, it, atom) > 0 for v in vn)]


def _dist(d: dict, atom: dict) -> float:
    """Distance of an item from the MoH value set."""
    return min(_gap(v, d, atom) for v in atom["vn"])


def _mirror_num(vv, ff, rule: str, log: bool) -> tuple[tuple[float, float] | None, str]:
    """Unrounded decoy interval (lo, hi) in the atom's unit and the rule actually used, or (None, reason)."""
    if log:                                   # geometric, in log space: 'auto' and 'mirror_geom' are the same rule
        if vv.lo <= 0 or ff.lo <= 0:
            return None, "không phản chiếu hình học được (giá trị ≤ 0)"
        k = 2 if rule == "mirror_far" else 1
        cv = math.sqrt(vv.lo * vv.hi)
        used = "mirror_far" if k == 2 else "mirror_geom"
        return (cv ** (k + 1) / ff.hi ** k, cv ** (k + 1) / ff.lo ** k), used
    cv, cf, w = (vv.lo + vv.hi) / 2, (ff.lo + ff.hi) / 2, ff.hi - ff.lo
    arith, used = 2 * cv - cf, "mirror_arith"
    if rule == "mirror_far":
        c, used = 3 * cv - 2 * cf, "mirror_far"
    elif rule == "mirror_geom" or arith - w / 2 <= 0:
        if cf <= 0:
            return None, "không phản chiếu được (giá trị nước ngoài ≤ 0)"
        c, used = cv * cv / cf, "mirror_geom"
    else:
        c = arith
    if c - w / 2 <= 0:
        return None, f"{used} cho giá trị ≤ 0"
    return (c - w / 2, c + w / 2), used


def _mirror(atom: dict, rule: str) -> tuple[dict | None, str, dict | None]:
    """(unrounded decoy item, rule used, rounding context for num) or (None, reason, None)."""
    kind = atom["value_kind"]
    conf = _conflicting(atom)
    if not conf:
        return None, "không có giá trị nước ngoài xung đột", None
    vn = atom["vn"]
    f, v = min(((f, v) for f in conf for v in vn), key=lambda p: _gap(p[1], p[0], atom))
    if kind == "bp":
        k = 3 if rule == "mirror_far" else 2          # far: v + 2(v - f)
        s, d = k * v["sys"] - (k - 1) * f["sys"], k * v["dia"] - (k - 1) * f["dia"]
        return {"sys": s, "dia": d, "text": f"{s:g}/{d:g} mmHg"}, ("mirror_far" if k == 3 else "mirror_arith"), None
    if kind != "num":
        return None, f"value_kind={kind}: mồi do người/agent đề xuất rồi check_decoy", None
    vv, ff = in_atom_unit(v, atom), in_atom_unit(f, atom)
    if vv is None or ff is None:
        return None, "không quy đổi được về đơn vị của mẩu", None
    iv, used = _mirror_num(vv, ff, rule, log_scale(atom))
    if iv is None:
        return None, used, None
    nd = _decimals(vv.lo, vv.hi, ff.lo, ff.hi)
    c = sum(iv) / 2
    if used == "mirror_geom":
        nd = max(nd, 1 if c < 10 else 0)
    lo, hi = round(iv[0], nd), round(iv[1], nd)
    if lo <= 0:
        return None, f"{used}: phản chiếu cho giá trị ≤ 0", None
    ctx = {"c": c, "cv": (vv.lo + vv.hi) / 2, "nd0": _decimals(v["lo"], v["hi"], f["lo"], f["hi"])}
    return num_item(lo, hi, atom.get("unit")), used, ctx


def mirror_decoy(atom: dict, rule: str = "auto") -> tuple[dict | None, str]:
    """(unrounded decoy ValueItem dict, rule) or (None, reason) for num/bp atoms.
    rule "auto" = mirror_arith, or mirror_geom when the arithmetic reflection is not positive (always mirror_geom for
    log-scale units); "mirror_geom" and "mirror_far" (twice the foreign distance, other side) are the pre-specified
    fallbacks used by choose_decoy. num values are at the decimals of the converted inputs (see decoy_candidates for
    the rounding)."""
    d, used, _ = _mirror(atom, rule)
    return d, used


def decoy_candidates(atom: dict, rule: str = "auto") -> tuple[list[tuple[dict, str, str]], str]:
    """Pre-specified candidates of one rule, in the order choose_decoy tries them: [(decoy, rule, rounding)], and the
    reason when there is none. rounding: "none" (bp, or a num mirror already on the 2-significant-digit grid),
    "step <s>" (rounded on the nice grid, nearest then away from the MoH value; kept only on the same side of the
    MoH value and at a distance within BAND of the unrounded mirror's) or "raw" (the unrounded mirror, always last)."""
    raw, used, ctx = _mirror(atom, rule)
    if raw is None:
        return [], used
    if ctx is None:
        return [(raw, used, "none")], used
    steps = nice_steps(ctx["c"], ctx["nd0"])
    lo, hi = raw["lo"], raw["hi"]
    if all(round_to(x, steps[-1]) == x for x in (lo, hi)):
        return [(raw, used, "none")], used
    d0 = _dist(raw, atom)
    up = ctx["c"] > ctx["cv"]
    away = ROUND_CEILING if up else ROUND_FLOOR
    out: list[tuple[dict, str, str]] = []
    for s in steps:
        for mode in (ROUND_HALF_UP, away):
            a, b = _round_dir(lo, s, mode), _round_dir(hi, s, mode)
            if a <= 0 or (a == b) != (lo == hi):          # never 0, never collapses an interval (or splits a point)
                continue
            if (a + b) / 2 == ctx["cv"] or ((a + b) / 2 > ctx["cv"]) != up:   # never crosses to the other side
                continue
            d = num_item(a, b, raw["unit"])
            r = _dist(d, atom) / d0 if d0 > 0 else math.inf
            if below(r, BAND[0]) or below(BAND[1], r) or any(d == x[0] for x in out):
                continue
            out.append((d, used, f"step {fmt_num(s)}"))
    out.append((raw, used, "raw"))
    return out, used


def choose_decoy_detail(atom: dict) -> tuple[dict | None, str, str | None]:
    """(decoy, rule, rounding) or (None, reasons, None). Pre-specified order: rules auto (arith, or geom if not
    positive; geom for log-scale units) -> mirror_geom -> mirror_far; within each rule the candidates of
    decoy_candidates. Returns the first decoy that passes check_decoy (clear of the MoH set and of ANY recorded
    source, incl. older foreign versions and derived values, by ≥ 2·tolerance-without-decoy for num/bp, and not
    making the atom indistinguishable). Record older foreign versions (e.g. JNC8) in `foreign` so they count."""
    reasons: list[str] = []
    tried: list[tuple] = []
    for r in RULES:
        cands, why = decoy_candidates(atom, r)
        if not cands:
            reasons.append(why)
            continue
        for d, used, rounding in cands:
            key = tuple(d.get(k) for k in ("lo", "hi", "sys", "dia"))
            if key in tried:                    # same value from another rule / rounding: already rejected
                continue
            tried.append(key)
            if not check_decoy(dict(atom, decoy=[d])):
                return d, used, rounding
            reasons.append(f"{used}: trùng nguồn/không phân biệt")
    return None, "; ".join(dict.fromkeys(reasons)), None


def choose_decoy(atom: dict) -> tuple[dict | None, str]:
    """(decoy, rule) or (None, reasons): choose_decoy_detail without the rounding."""
    d, rule, _ = choose_decoy_detail(atom)
    return d, rule


def check_decoy(atom: dict) -> list[str]:
    """Problems with atom['decoy'] (empty list = acceptable).
    num/bp: distances are measured with tol0 = compute_tolerance of the atom WITHOUT its decoy (never with a
    tolerance the decoy itself narrowed). A decoy is rejected at gap 0, or gap < 2·tol0 (below: binary noise at the
    boundary does not count), from any MoH item, any recorded foreign or superseded value — derived values included:
    they are known values a model can compute, a decoy near one is not a chance control, and the registered
    with_derived sensitivity would grade it as that source — or any MoH value of a neighbouring context
    (Atom.moh_neighbour). With tol0 = 0 a num/bp decoy at a finite gap from the MoH set is rejected (it would set the
    tolerance itself; such atoms have no conflicting or distinct superseded value, so no role for a decoy). schedule /
    drugs / cat: only gap 0 is rejected."""
    probs = []
    kind = atom.get("value_kind")
    vn = atom.get("vn") or []
    srcs = [it for f in atom.get("foreign") or [] for it in f["values"]]
    srcs += [it for s in atom.get("superseded") or [] for it in s["values"]]
    nbs = [it for nb in atom.get("moh_neighbour") or [] for it in nb.get("values") or []]
    tol0 = compute_tolerance(dict(atom, decoy=[])) if kind in ("num", "bp") else 0.0

    def near(x: dict, d: dict) -> bool:
        g = _gap(x, d, atom)
        return g == 0 or below(g, 2 * tol0)

    for d in atom.get("decoy") or []:
        name = d.get("text") or d
        gaps = [_gap(v, d, atom) for v in vn]
        if any(g == 0 for g in gaps):
            probs.append(f"mồi {name} trùng tập giá trị Bộ Y tế")
        elif any(near(v, d) for v in vn):
            probs.append(f"mồi {name} nằm trong vùng dung sai của giá trị Bộ Y tế (dung sai không mồi {tol0:g})")
        elif kind in ("num", "bp") and tol0 == 0 and any(math.isfinite(g) for g in gaps):
            probs.append(f"mồi {name} sẽ tự đặt dung sai (mẩu không có giá trị nào khác Bộ Y tế ở khoảng cách hữu hạn, "
                         "dung sai không mồi 0): mẩu này không dùng mồi")
        if any(_gap(s, d, atom) == 0 for s in srcs):
            probs.append(f"mồi {name} trùng một nguồn đã ghi")
        elif any(near(s, d) for s in srcs):         # windows overlap: would be graded as that source
            probs.append(f"mồi {name} nằm trong vùng dung sai của một nguồn đã ghi (dung sai không mồi {tol0:g})")
        if any(near(x, d) for x in nbs):
            probs.append(f"mồi {name} chạm giá trị Bộ Y tế ở bối cảnh lân cận")
    if atom.get("decoy"):
        without = dict(atom, decoy=[])
        before = conflict_status(dict(without, tolerance=compute_tolerance(without)))
        after = conflict_status(dict(atom, tolerance=compute_tolerance(atom)))
        if after == "indistinguishable" and before != "indistinguishable":   # only when the decoy itself causes it
            probs.append("mồi làm mẩu thành indistinguishable")
    return probs


def finalize(atom: dict) -> dict:
    """Recompute tolerance and conflict_status (never hand-set them)."""
    a = dict(atom)
    a["tolerance"] = compute_tolerance(a)
    a["conflict_status"] = conflict_status(a)
    return a
