"""Decoy values (proposal §1.2, §4.2): the chance-coincidence control for H1.

A decoy has the same kind and unit as the MoH value and lies about as far from it as the conflicting foreign value,
but belongs to no known source. For numeric and blood-pressure atoms the decoy is generated by a fixed rule so that
nobody chooses it after seeing model outputs:

  num  "mirror_arith": reflect the nearest conflicting foreign interval through the nearest MoH value
       (centre c_d = 2·c_vn − c_f, same width as the foreign interval), rounded to the inputs' precision;
       if that is ≤ 0, "mirror_geom": c_d = c_vn² / c_f (same ratio on the other side).
  bp   "mirror_arith" per component: 2·vn − foreign.
For schedule / drugs / cat atoms the decoy is a real-looking alternative proposed by a person or agent;
`check_decoy` rejects it if it equals any recorded source value or makes the atom indistinguishable.

`finalize(atom)` recomputes tolerance and conflict_status with vnsoc.grade (the single definition) — call it last.
"""
from __future__ import annotations

from decimal import Decimal

from vnsoc.grade import _gap, compute_tolerance, conflict_status


def _decimals(*xs: float) -> int:
    d = 0
    for x in xs:
        e = Decimal(str(float(x))).normalize().as_tuple().exponent
        d = max(d, -e if isinstance(e, int) and e < 0 else 0)
    return d


def in_atom_unit(item: dict, atom: dict):
    """A num ValueItem as nv.Num in the atom's unit (context: weight_kg, mg_per_ml, analyte...), or None."""
    from vnsoc import normalize_vi as nv

    unit = atom.get("unit")
    return nv.Num(float(item["lo"]), float(item["hi"]), item.get("unit") or unit).to(unit, atom.get("context") or {})


def _conflicting(atom: dict) -> list[dict]:
    vn = atom.get("vn") or []
    return [it for f in atom.get("foreign") or [] for it in f["values"] if all(_gap(v, it, atom) > 0 for v in vn)]


def mirror_decoy(atom: dict) -> tuple[dict | None, str]:
    """(decoy ValueItem dict, rule) or (None, reason) for num/bp atoms."""
    kind = atom["value_kind"]
    conf = _conflicting(atom)
    if not conf:
        return None, "không có giá trị nước ngoài xung đột"
    vn = atom["vn"]
    f, v = min(((f, v) for f in conf for v in vn), key=lambda p: _gap(p[1], p[0], atom))
    if kind == "bp":
        return {"sys": 2 * v["sys"] - f["sys"], "dia": 2 * v["dia"] - f["dia"],
                "text": f"{2 * v['sys'] - f['sys']:g}/{2 * v['dia'] - f['dia']:g} mmHg"}, "mirror_arith"
    if kind != "num":
        return None, f"value_kind={kind}: mồi do người/agent đề xuất rồi check_decoy"
    unit = atom.get("unit")
    vv, ff = in_atom_unit(v, atom), in_atom_unit(f, atom)
    if vv is None or ff is None:
        return None, "không quy đổi được về đơn vị của mẩu"
    cv, cf, w = (vv.lo + vv.hi) / 2, (ff.lo + ff.hi) / 2, ff.hi - ff.lo
    nd = _decimals(vv.lo, vv.hi, ff.lo, ff.hi)
    c, rule = 2 * cv - cf, "mirror_arith"
    if c - w / 2 <= 0:
        if cf <= 0:
            return None, "không phản chiếu được (giá trị nước ngoài ≤ 0)"
        c, rule = cv * cv / cf, "mirror_geom"
        nd = max(nd, 1 if c < 10 else 0)
    lo, hi = round(c - w / 2, nd), round(c + w / 2, nd)
    if lo <= 0:
        return None, "phản chiếu cho giá trị ≤ 0"
    text = f"{lo:g}" if lo == hi else f"{lo:g}–{hi:g}"
    return {"lo": lo, "hi": hi, "unit": unit, "text": f"{text} {unit}".strip()}, rule


def check_decoy(atom: dict) -> list[str]:
    """Problems with atom['decoy'] (empty list = acceptable)."""
    probs = []
    vn = atom.get("vn") or []
    srcs = [it for f in atom.get("foreign") or [] for it in f["values"]]
    srcs += [it for s in atom.get("superseded") or [] for it in s["values"]]
    for d in atom.get("decoy") or []:
        if any(_gap(v, d, atom) == 0 for v in vn):
            probs.append(f"mồi {d.get('text') or d} trùng tập giá trị Bộ Y tế")
        if any(_gap(s, d, atom) == 0 for s in srcs):
            probs.append(f"mồi {d.get('text') or d} trùng một nguồn đã ghi")
    if atom.get("decoy") and conflict_status(dict(atom, tolerance=compute_tolerance(atom))) == "indistinguishable":
        probs.append("mồi làm mẩu thành indistinguishable")
    return probs


def finalize(atom: dict) -> dict:
    """Recompute tolerance and conflict_status (never hand-set them)."""
    a = dict(atom)
    a["tolerance"] = compute_tolerance(a)
    a["conflict_status"] = conflict_status(a)
    return a
